#!/bin/bash

# Create formal solution files
~/Technion_projects/mtm/ex0/part1/mtm_sol < test1.in > test1.out
~/Technion_projects/mtm/ex0/part1/mtm_sol < test2.in > test2.out
~/Technion_projects/mtm/ex0/part1/mtm_sol < test3.in > test3.out
~/Technion_projects/mtm/ex0/part1/mtm_sol < test4.in > test4.out
~/Technion_projects/mtm/ex0/part1/mtm_sol < test5.in > test5.out
~/Technion_projects/mtm/ex0/part1/mtm_sol < test6.in > test6.out
~/Technion_projects/mtm/ex0/part1/mtm_sol < test7.in > test7.out
~/Technion_projects/mtm/ex0/part1/mtm_sol < test8.in > test8.out

# Create self solution files and compare
~/Technion_projects/mtm/ex0/part1/mtm_tot < test1.in > tmp1.out
diff tmp1.out test1.out
~/Technion_projects/mtm/ex0/part1/mtm_tot < test2.in > tmp2.out
diff tmp2.out test2.out
~/Technion_projects/mtm/ex0/part1/mtm_tot < test3.in > tmp3.out
diff tmp3.out test3.out
~/Technion_projects/mtm/ex0/part1/mtm_tot < test4.in > tmp4.out
diff tmp4.out test4.out
~/Technion_projects/mtm/ex0/part1/mtm_tot < test5.in > tmp5.out
diff tmp5.out test5.out
~/Technion_projects/mtm/ex0/part1/mtm_tot < test6.in > tmp6.out
diff tmp6.out test6.out
~/Technion_projects/mtm/ex0/part1/mtm_tot < test7.in > tmp7.out
diff tmp7.out test7.out
~/Technion_projects/mtm/ex0/part1/mtm_tot < test8.in > tmp8.out
diff tmp8.out test8.out